name: tienda_labiales
description: Aplicación de tienda de labiales con carrito de compras

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Versión actualizada para compatibilidad con Firebase

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  cached_network_image: ^3.2.3
  # Dependencias de Firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.17.0
  mockito: ^5.4.2  # (Opcional, solo para testing)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Versión actualizada

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/saint.jpeg
    - lib/assets/spice.jpeg
    - lib/assets/brownie.jpeg
    - lib/assets/sweet chocolate.jpeg
    - lib/assets/maroon.jpeg
    - lib/assets/hazelnut.jpeg
